lib/ripper-tags.rb, test/test_cli.rb
This is for compatibility with `ctags` CLI.
Fixes #35
/cc @toupeira
=> Allow an optional `--tag--relative=yes` value for the flag

lib/ripper-tags.rb
I noticed that running ripper-tags -v is still showing 1.2, even tho I was using the 1.3 release.
Fixed updating the version to 1.3
=> update version to 1.3

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
Ensures that the tag's `name` property doesn't include the namespace.
Fixes #32
=> Fix extracting name of namespaced constant

ripper-tags.gemspec, script/bootstrap, script/release, script/test
* Gemspec now inherits library version from source code
* Gem now only includes runtime files
* `script/bootstrap` & `script/test`
* `script/release`
=> Improve gemspec and add dev scripts

lib/ripper-tags.rb
ctags implements a `--xcmd-<LANG>=COMMAND` option that can be used to specify a command as an external parser for specific language.
The external parser needs to implement `--tag-kinds` for compatibility.
https://github.com/universal-ctags/ctags/blob/master/docs/xcmd.rst
Fixes #28
/cc @UmkaDK
=> Implement `--tag-kinds` option for compatibility as ctags external parser

lib/ripper-tags.rb, lib/ripper-tags/default_formatter.rb, lib/ripper-tags/emacs_formatter.rb, lib/ripper-tags/vim_formatter.rb, test/test_cli.rb, test/test_formatters.rb
For each namespaced class, module, or constant, this adds another entry to the output with the constant name expanded to be fully qualified.
Fixes #27
/cc @mweaverh
=> Support `--extra=q` option to add fully qualified constant names

Gemfile, lib/ripper-tags/json_formatter.rb, ripper-tags.gemspec, test/test_formatters.rb
* Output one big JSON array instead of one JSON hash per each line of output. This can simplify parsing for the consumer. **Backwards incompatible.**
* Drops strict yajl-ruby dependecy. Now tries to load "yajl" and falls back to "json".
/cc @tmm1
=> Improve JSON formatter

lib/ripper-tags/default_formatter.rb, test/test_formatters.rb
This is to finish what was started in https://github.com/tmm1/ripper-tags/pull/36 . It makes `--tag-relative` option work when the path to tags file is absolute.
=> Handle relative path option when path to tags file is absolute

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
Fixed exception: "NoMethodError: undefined method `on_attr_protected' for
<RipperTags::Visitor:0x000000022f56c8>`"
=> Fix "undefined method" exception for private/protected/public clauses

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
A bare `!condition` works when inside a method definition, or when part of an `if` clause, but when `!condition` was used either at the top-level or in an `elsif` clause, the missing `on_!` callback caused a crash.
```
$ cat bang.rb
!true
$ ripper-tags bang.rb
/Users/nathan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ripper-tags-0.3.4/lib/ripper-tags/parser.rb:257:in `process': undefined method `on_!' for #<RipperTags::Visitor:0x007fceea8bf2c0> (NoMethodError)
from /Users/nathan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ripper-tags-0.3.4/lib/ripper-tags/parser.rb:234:in `initialize'
from /Users/nathan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ripper-tags-0.3.4/lib/ripper-tags/data_reader.rb:152:in `new'
from /Users/nathan/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/ripper-t …
```
=> Fix crash when parsing a `!condition`

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
This adds support for methods declared with either of
| style | example |
| - | - |
| [Module.delegate](http://www.rubydoc.info/gems/activesupport/Module%3Adelegate) |  `delegate :this, to: :that` |
| [Forwardable.def_delegator](http://ruby-doc.org/stdlib-2.0.0/libdoc/forwardable/rdoc/Forwardable.html#method-i-def_instance_delegator) | `def_delegator :target, :old_name, :new_name` |
| [Forwardable.def_delegators](http://ruby-doc.org/stdlib-2.0.0/libdoc/forwardable/rdoc/Forwardable.html#method-i-def_instance_delegators) | `def_delegators :target, :one, :two, :three` |
All of these will show up as regular methods, declared at the line where their identifier was listed. For `def_delegator`, the actual method name added is its last argument (using original name if alias not provided), while …
=> Add support for `delegate`, `def_delegator` and `def_delegators`

lib/ripper-tags.rb, lib/ripper-tags/default_formatter.rb, lib/ripper-tags/vim_formatter.rb, test/test_formatters.rb
I was using tagbar with ripper-tags, but I couldn't jump to the tag definition because ripper-tags output doesn't have the line number information.
Not sure if this is just my need, `ripper-tags` might consider adding an option to support line number information. If you think this is a good feature, I could open another PR to add the `-l` option.
Thanks.
=> Add option to include line number for vim formatter

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
We could write Ruby code like this because `def` will return the defined method itself:
``` ruby
private_class_method def self.foo
'bar'
end
```
Previously, `ripper-tags` won't recognize them and generate the concrete tag, this PR will add the support.
=> Support one-line method declaration with access

lib/ripper-tags.rb, lib/ripper-tags/data_reader.rb, test/test_cli.rb, test/test_data_reader.rb
Thanks for this great project! I made this change because I have large project trees with mixed Ruby and non-Ruby files, and some of the Ruby files do not end in `.rb`.
I have a script that figures out all the Ruby files. There may be thousands of files to process, with long relative pathnames, so they simply won't fit on the command line. And even with `xargs` multiple passes would be required.
With this new option I can put all the pathnames into a file and process them all in 1 pass. It uses the short-form `-L` to coincide with the `ctags` tool.
I hope you find it useful.
=> Support an input file of pathnames

lib/ripper-tags.rb, test/test_cli.rb
This addresses an issue raised in #54: to have an option that turns on tolerant mode, ignoring any unknown commandline options.
=> Support `--ignore unsupported-options`

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
this was exposed when trying to parse https://github.com/flyerhzm/bullet/blob/master/lib/bullet.rb#L36-L38
```ruby
available_notifiers = UniformNotifier::AVAILABLE_NOTIFIERS.map { |notifier| "#{notifier}=" }
available_notifiers << { :to => UniformNotifier }
delegate *available_notifiers
```
=> fixes an issue when `delegate *options` was used

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
Hi!
This very simple change allows the parser to emit tags not only for attr_* methods but also their module/class counterparts mattr_* and cattr_*.
Thanks for creating ripper-tags, just found it and fully replaced ctags for my ruby development in vim.
Cheers,
Frank
=> Parse mattr_* and cattr_* module accessors, writers and readers

lib/ripper-tags/data_reader.rb, test/test_data_reader.rb
If there is an unreadable directory considered by `ripper-tags`, an exception is raised:
```
.../lib/ripper-tags/data_reader.rb:59:in `open': Permission denied @ dir_initialize - foo/bar (Errno::EACCES)
from .../lib/ripper-tags/data_reader.rb:59:in `entries'
from .../lib/ripper-tags/data_reader.rb:59:in `resolve_file'
from .../lib/ripper-tags/data_reader.rb:63:in `block in resolve_file'
```
(tested with 0.6.0)
This PR gracefully handles such directories, by skipping them (and logging if `--verbose` is given).
To reproduce the existing behaviour, run:
```
$ mkdir -p a/b
$ touch a/b/c.rb
$ chmod 355 a/b
$ ripper-tags --tag-file=/dev/null --recursive --verbose a # Errors
```
with this PR, we now have
```
$ bundle exec bin/ripper-tags --tag-file=/dev/null --recursive --verbose a
Ignoring …
```
=> Gracefully handle unreadable directories

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
=> Skip emitting tags for scopes with blank name

lib/ripper-tags.rb, test/test_cli.rb
Exhuberant Ctags has `--recurse` instead of `--recursive`, this just introduces `--recurse=[yes|no]`  to the CLI  to make the interface compatible (will avoid hacks with generic tags plugins in editors, in my case the well known https://github.com/ludovicchabant/vim-gutentags):
```
$ ctags --help | grep recur
-R   Equivalent to --recurse.
--recurse=[yes|no]
```
```
$ bundle exec bin/ripper-tags --help | grep recur
-R, --recursive                  Descend recursively into subdirectories
--recurse=[yes|no]           Alias for --recursive
--all-files                  Parse all files in recursive mode (default: parse `*.rb' files)
```
Behaviour is the same as `--recursive`:
```
$ bundle exec bin/ripper-tags --recurse --verbose
Parsing file `test/test_ripper_tags.rb'
Parsing file …
```
=> Add ctags compatible --recurse alias

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
Fixes #94 
This hooks into `on_command` (which does a lot of work already) and handles any unrecognized name by checking if what follows is a method definition. And if so, passes it on to `on_def`.
=> Handle decorators/method modifiers

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
As discussed here: https://github.com/tmm1/ripper-tags/issues/94#issuecomment-551546094
Now this code will generate tags:
```ruby
some_cool_dsl_method do
def my_method
end
end
```
Tested in some big projects, seems to work.
Update: also contains fix from #79 since basically it requires that change.
=> Generate tags for methods defined in blocks

lib/ripper-tags/parser.rb, test/test_ripper_tags.rb
I updated to 1.0 today because I saw the announcement in Ruby Weekly last week. I am now getting a NoMethodError where previously there was no error when parsing (on v.0.9.1):
```
NoMethodError parsing `myfile.rb': undefined method `first' for nil:NilClass
```
To be clear, I can still use it but this particular construction seems to throw the parser.
I've made a minimal test case that recreates the behavior.
```ruby
class C
def object = Object.new
delegate :thing, to: :object
delegate :thing=, to: :object
%i(other).each do |k|
delegate k, to: :object
delegate :"#{k}", to: :object
end
%(foo).each do |k|
delegate k, :"#{k}=", to: :object
end
end
```
=> Fix parse error for delegate statements with dynamic arguments
